server:
  port: 8084

spring:
  application:
    name: organization-service

  datasource:
    url: jdbc:h2:mem:organizationdb
    driverClass: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
    settings:
      web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo-realm

keycloak:
  realm: demo-realm
  server-url: http://localhost:8080
  admin:
    client-id: user-service
    client-secret: user-service-secret

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
