server:
  port: 8081

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: booking
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: booking
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

logging:
  level:
    root: INFO
